mysql:
  username: root
  password: 'hmf!1008'
  path: '127.0.0.1:3306'
  db-name: 'admin'
  config: 'charset=utf8&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false